# Tugas Praktikum
 - NAMA: Farhannivta Ramadhana
 - NIM : 123230139
 - Kelas: IF-D

1. Buatlah matriks 3x3 dengan elemen berupa bilangan berurutan dari 1 hingga 9. Cetak Hasilnya

In [1]:
# import numpy
import numpy as np

matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2. Definisikan dua matriks 2x2
   A = [[1, 2], [3,4]]
   B = [[5, 6], [7,8]]
   Hitung hasil penjumlahan dari kedua matriks tersebut.

In [2]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

matrixHasilJumlah = A + B

print(matrixHasilJumlah)

[[ 6  8]
 [10 12]]


3. Hitunglah hasil perkalian matriks berikut:
   C = [[1,0], [0,1]]
   D = [[2,3], [4,5]]
   Cetak hasilnya dalam bentuk matriks

In [3]:
C = np.array([[1,0], [0,1]])
D = np.array([[2,3], [4,5]])

matrixHasilKali = C.dot(D)

print(matrixHasilKali)

[[2 3]
 [4 5]]


4. Diberikan matrix 2x3 berikut:
   E = [[1,2,3], [4,5,6]]
   Lakukan transpose dan cetak hasilnya.

In [4]:
E = np.array([[1,2,3], [4,5,6]])
ET = E.T

print(ET)

[[1 4]
 [2 5]
 [3 6]]


5. Selesaikan sistem persamaan linier berikut menggunakan matriks:
   x + 2y = 10
   3x + 4y = 24

In [5]:
F = np.array([[1, 2], [3, 4]])
G = np.array([10, 24])

solution = np.linalg.solve(F, G)

print(solution)

[4. 3.]


6. Diberikan dua matriks
   A = [[1,2],[3,4]]
   B = [[5,6],[7,8]]
   Gabungkan kedua matriks:
   - Secara horizontal.
   - Secara vertikal

In [6]:
ABH = np.hstack((A, B))
ABV = np.vstack((A, B))

print(ABH)
print(ABV)

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


7. Definisikan array ID berikut:
   X = [[1,2,3], [4,5,6]]
   Ubah array tersebut menjadi matriks:
   - Matriks 2x3
   - Matriks 3x2

In [10]:
X = np.array([[1,2,3], [4,5,6]])

Xrs2x3 = np.resize(X, (2,3))
Xrs3x2 = np.resize(X, (3,2))

print(Xrs2x3)
print(Xrs3x2)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
