# Pertemuan 2 - Numpy

In [1]:
import numpy as np

In [2]:
vector = np.array([1,2,3])
matrix = np.array([[1,2,3], [4,5,6]])
ndarray = np.array([[1,2], [3,4], [5,6], [7,8]])

In [3]:
print(vector)
print(matrix)
print(ndarray)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [4]:
matrix[:, 0]

array([1, 4])

## Operasi aritmatika Numpy

In [5]:
# Array awal
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])

In [6]:
# Penjumlahan
c = a + b
print(c)

[[ 6  8]
 [10 12]]


In [7]:
# Pengurangan
d = b - a
print(d)

[[4 4]
 [4 4]]


In [8]:
# Perkalian
e = np.dot(a,b)
print(e)

[[19 22]
 [43 50]]


## Sistem Persamaan Linear
- x+2y=10
- 3x+4y=24
- 2x+5y=23

In [9]:
f = np.array([[1,2], [3,4], [2,5]])
g = np.array([10,24,23])

In [10]:
x = np.linalg.solve(f,g)
print(x)

LinAlgError: Last 2 dimensions of the array must be square

## Penggabungan dua matrix

In [12]:
H = np.hstack((a,b))
V = np.vstack((a,b))
print(H)
print(V)

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
